name: Socket Security

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  socket-security:
    name: Socket Supply Chain Security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Socket CLI
        run: npm install -g @socketsecurity/cli

      - name: Run Socket Security Scan
        env:
          SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
        run: |
          if [ -n "$SOCKET_SECURITY_API_KEY" ]; then
            echo "Running Socket security scan..."
            npx socket-npm audit || echo "Socket scan completed with findings"
          else
            echo "⚠️ SOCKET_SECURITY_API_KEY not set. Skipping Socket scan."
            echo "To enable Socket scanning, add SOCKET_SECURITY_API_KEY to repository secrets."
          fi

      - name: Socket Report Summary
        if: always()
        run: |
          echo "Socket Security scan completed"
          echo "For detailed reports, visit: https://socket.dev/dashboard"
